#!/usr/bin/env bash
# https://github.com/betterlockscreen/betterlockscreen/blob/master/examples/betterlockscreenrc
# Comments for colors are added to see the color in the IDE
# shellcheck disable=SC2034
display_on=0
span_image=false
lock_timeout=600
fx_list=(dim blur dimblur)
dim_level=50
blur_level=1
pixel_scale=10,1000
solid_color=333333 #333333
wallpaper_cmd="feh --bg-fill"

# Use `i3lock` for betterlockscreen, `i3lock-color` for blurred screenshot
i3lockcolor_bin="i3lock"

# Gruvbox theme
# https://github.com/morhetz/gruvbox
# https://camo.githubusercontent.com/410b3ab80570bcd5b470a08d84f93caa5b4962ccd994ebceeb3d1f78364c2120/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67
BLANK=282828aa   #282828
CLEAR=282828     #282828
DEFAULT=928374   #928374
TEXT=ebdbb2      #ebdbb2
WRONG=fb4934     #fb4934
VERIFYING=458588 #458588
KEY_INPUT=fabd2f #fadb2f
BACKSPACE=8ec07c #8ec07c

loginbox=00000066
loginshadow=00000000
locktext="Locked"
font="FiraCode Nerd Font"
ringcolor=$DEFAULT
insidecolor=$BLANK
separatorcolor=$DEFAULT
ringvercolor=$VERIFYING
insidevercolor=$CLEAR
ringwrongcolor=$WRONG
insidewrongcolor=$CLEAR
timecolor=$TEXT
time_format="%H:%M:%S"
greetercolor=$TEXT
layoutcolor=$TEXT
keyhlcolor=$KEY_INPUT
bshlcolor=$BACKSPACE
verifcolor=$TEXT
wrongcolor=$TEXT
modifcolor=$TEXT
bgcolor=000000ff
# vim: ft=sh
